修复Cursor Dance 和 Autoplay 在使用Ctrl+Enter时同时启用
MATRIX-feather/osu pull request #5
Opened 2021-01-17 07:20 UTC by PercyDan54

2021-01-24 01:11 UTC, MATRIX-feather commented
我这里试了一周都没有成功复现，或许检查一下你那边的实现方式?

2021-01-24 02:39 UTC, PercyDan54 commented
> 我这里试了一周都没有成功复现，或许检查一下你那边的实现方式?

就是我把cursor dance放在了auto前面
然后FirstOrDefault()就取它了

2021-01-25 17:20 UTC, MATRIX-feather commented
这样的话那我就把这个pr关掉了

2021-03-01 13:37 UTC, MATRIX-feather requested changes

2021-03-01 13:37 UTC, MATRIX-feather commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +                removeAutoModOnResume = true;
这里可以改成下面的样子:
```
if (!mods.Any(m => m is ModAutoplay))
{
    Mods.Value = mods.Append(autoplayMod).ToArray();
    removeAutoModOnResume = true;
}
```
然后下面的`Play:`就可以去掉了

2021-03-01 14:07 UTC, MATRIX-feather approved these changes

2021-03-01 14:07 UTC, merged