修复Cursor Dance短转盘鬼畜
MATRIX-feather/osu pull request #6
Opened 2021-01-25 10:07 UTC by PercyDan54

没错，又是这张万恶的图：https://osu.ppy.sh/beatmapsets/814850#osu/1901200

2021-01-25 17:18 UTC, MATRIX-feather requested changes

2021-01-25 17:18 UTC, MATRIX-feather commented on osu.Game.Rulesets.Osu/Replays/OsuDanceAutoGenerator.cs
> +                buttonIndex = 0;
这里是不是少了点什么? 我这边在编译时提示`当前上下文中不存在名称"buttonIndex"`

2021-01-26 01:03 UTC, PercyDan54 commented on osu.Game.Rulesets.Osu/Replays/OsuDanceAutoGenerator.cs
> +                buttonIndex = 0;
初始化时int 一个

2021-01-26 12:32 UTC, MATRIX-feather approved these changes

2021-01-26 12:35 UTC, merged