Mvis在Discord状态下显示歌名
MATRIX-feather/osu pull request #7
Opened 2021-02-01 14:40 UTC by PercyDan54

让Mvis在Discord状态下显示歌名，随着设置显示Unicode歌名

2021-02-01 15:54 UTC, MATRIX-feather requested changes

2021-02-01 15:54 UTC, MATRIX-feather commented on osu.Game/Users/UserActivity.cs
> +            public override string Status => $@"正在听 {(Unicode ? Beatmap.BeatmapSet.Metadata.TitleUnicode : Beatmap.BeatmapSet.Metadata.Title)} - {(Unicode ? Beatmap.BeatmapSet.Metadata.ArtistUnicode
这部分在 [DiscordRichPresence](https://github.com/MATRIX-feather/osu/blob/stable/osu.Desktop/DiscordRichPresence.cs#L148) 处已经有实现了，不需要设置Status，在那里改一下实现就行

2021-02-01 15:54 UTC, MATRIX-feather commented on osu.Game/Screens/Mvis/MvisScreen.cs
> +        private void onUseUnicodeChanged(ValueChangedEvent<bool> v)
把这里的`ValueChangedEvent<bool> v`去掉，在函数内获取，接着设置activity的值。这样无论从上面`useUnicode.BindValueChanged`还是下面`onBeatmapChanged`调用都会更方便一些

2021-02-01 15:54 UTC, MATRIX-feather commented on osu.Game/Screens/Mvis/MvisScreen.cs
> +            useUnicode.BindValueChanged(onUseUnicodeChanged, true);
在上面`Beatmap.BindValueChanged(OnBeatmapChanged, true);`中已经设置过一次了，不需要重复调用

2021-02-02 00:51 UTC, PercyDan54 commented on osu.Game/Screens/Mvis/MvisScreen.cs
> +            useUnicode.BindValueChanged(onUseUnicodeChanged, true);
mvis界面也可以ctrl+o打开设置

2021-02-02 03:57 UTC, MATRIX-feather commented on osu.Game/Screens/Mvis/MvisScreen.cs
> +            useUnicode.BindValueChanged(onUseUnicodeChanged, true);
> mvis界面也可以ctrl+o打开设置

在设置界面调整后会自动触发`onUseUnicodeChanged`, `true`只是让他立即运行一次

2021-02-07 02:40 UTC, closed without merging